openapi: 3.0.3
info:
  title: Тудушка
  version: 2.0.0
paths:
  /login:
    get:
      summary: Проверить авторизацию пользователя
      description: Проверяет наличие токена
      tags:
        - Авторизация
        - Пользователь
      responses:
        200:
          description: Токен действителен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
    post:
      summary: Авторизоваться
      description: Авторизация пользователя, получить токен
      tags:
        - Авторизация
        - Пользователь
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                  description: Логин пользователя
                  example: userLogin
                password:
                  type: string
                  description: Пароль пользователя
                  example: userPassword12345678910
      responses:
        200:
          description: Пользователь успешно авторизовался
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /logout:
    get:
      summary: Разлогиниться
      description: Удаляет токен у пользователя
      tags:
        - Авторизация
        - Пользователь
      responses:
        204:
          description: Пользователь успешно разлогинился

  /users:
    post:
      summary: Создать нового пользователя
      description: Создает нового пользователя
      tags:
        - Пользователь
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  required: true
                  description: email пользователя
                  example: userLogin@google.com
                login:
                  type: string
                  required: true
                  description: Имя пользователя
                  example: userLogin
                password:
                  type: string
                  required: true
                  description: Пароль пользователя
                  example: userPassword12345678910
      responses:
        201:
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /users/{login}:
    patch:
      summary: Изменить существующего пользователя
      description: Изменяет существующего пользователя по login
      parameters:
        - $ref: '#/components/parameters/userLogin'
      tags:
        - Пользователь
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Новый email пользователя
                  required: false
                login:
                  type: string
                  description: Новое имя пользователя
                  required: false
                password:
                  type: string
                  description: Новый пароль пользователя
                  required: false
                oldPassword:
                  type: string
                  description: Текущий пароль пользователя
                  required: true
      responses:
        200:
          description: Пользователь успешно изменен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
    delete:
      summary: Удалить пользователя по login
      description: Удаляет пользователя по login
      parameters:
        - $ref: '#/components/parameters/userLogin'
      tags:
        - Пользователь
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  required: true
                  example: userSuperPassword12345678910
                  description: Текущий пароль пользователя
      responses:
        204:
          description: Пользователь успешно удален


  /users/{login}/todos:
    get:
      summary: Получить все тудушки пользователя
      parameters:
        - $ref: '#/components/parameters/userLogin'
      tags:
        - Пользователь
        - Тудушка
      responses:
        200:
          description: Получить все тудушки пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/todoItem'
    post:
      summary: Добавить тудушку пользователю
      parameters:
        - $ref: '#/components/parameters/userLogin'
      tags:
        - Пользователь
        - Тудушка
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  required: true
                  description: Описание тудушки
                  example: Описание новой тудушки
      responses:
        201:
          description: Тудушка успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'

  /todos/{id}:
    get:
      summary: Получить тудушку по id
      description: Возвращает тудушку по id
      tags:
        - Тудушка
      parameters:
        - $ref: '#/components/parameters/todoId'
      responses:
        200:
          description: Возвращает тудушку по id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'
    patch:
      summary: Апдейт тудушки по id
      description: Апдейт тудушки по id
      tags:
        - Тудушка
      parameters:
        - $ref: '#/components/parameters/todoId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  required: false
                  description: Новое описание тудушки
                  example: Новое описание тудушки
                isDone:
                  type: boolean
                  required: false
                  description: Новый статус тудушки
                  example: true
      responses:
        200:
          description: Тудушка успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'
    delete:
      summary: Удалить тудушку по id
      description: Удалить тудушку по id
      tags:
        - Тудушка
      parameters:
        - $ref: '#/components/parameters/todoId'
      responses:
        204:
          description: Тудушка успешно удалена

components:
  parameters:
    userLogin:
      in: path
      name: login
      required: true
      schema:
        type: string
        description: login пользователя

    todoId:
      in: path
      name: id
      required: true
      schema:
        type: number
        description: id тудушки

  schemas:
    id:
      type: number
      description: id сущности
      example: 1

    link:
      type: object
      properties:
        method:
          type: string
          description: http глагол
          example: GET
        link:
          type: string
          description: ссылка на действие
          example: /link/to/action

    user:
      description: пользователь
      type: object
      properties:
        login:
          type: string
          description: Логин пользователя
          example: userLogin
        email:
          type: string
          description: email пользователя
          example: userLogin@google.com
        createdAt:
          type: string
          description: Дата создания
          example: 2020-06-30T18:25:02.495Z
        updatedAt:
          type: string
          description: Дата последнего обновления
          example: 2020-06-30T18:25:02.495Z
        _links:
          type: object
          properties:
            getSelf:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: GET
                    link:
                      description: Ссылка на пользователя
                      example: /user/userLogin
            updateSelf:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: PATCH
                    link:
                      description: Ссылка на обновление пользователя
                      example: /user/userLogin
            removeSelf:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: DELETE
                    link:
                      description: Ссылка на удаление пользователя
                      example: /user/userLogin
            getTodos:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: GET
                    link:
                      description: Ссылка на получение тудушек пользователя
                      example: /user/userLogin/todos
            addTodo:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: POST
                    link:
                      description: Ссылка на добавление тудушек пользователю
                      example: /user/userLogin/todos

    todoItem:
      description: тудушка
      type: object
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/id'
            - description: id тудушки
        userId:
          allOf:
            - $ref: '#/components/schemas/id'
            - description: id пользователя, которому принадлежит тудушка
        description:
          type: string
          description: Описание задачи
        createdAt:
          type: string
          description: Дата создания
          example: 2020-06-30T18:25:02.495Z
        updatedAt:
          type: string
          description: Дата последнего обновления
          example: 2020-06-30T18:25:02.495Z
        isDone:
          type: boolean
          description: Статус задачи
          example: true
        _links:
          type: object
          properties:
            getSelf:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: GET
                    link:
                      description: Ссылка на тудушку
                      example: /todos/1
            updateSelf:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: PATCH
                    link:
                      description: Ссылка на обновление тудушки
                      example: /todos/1
            removeSelf:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: DELETE
                    link:
                      description: Ссылка на удаление тудушки
                      example: /todos/1
            getOwner:
              allOf:
                - $ref: '#/components/schemas/link'
                - properties:
                    method:
                      example: GET
                    link:
                      description: Ссылка на владельца тудушки
                      example: /users/userLogin