openapi: 3.0.3
info:
  title: Тудушка
  version: 1.0.0
paths:
  /users:
    post:
      summary: Создать нового пользователя
      description: Создает нового пользователя
      tags:
        - Пользователь
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  required: true
                  description: Имя пользователя
                  example: User
      responses:
        201:
          description: Пользователь создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  /users/{id}:
    patch:
      summary: Изменить существующего пользователя
      description: Изменяет существующего пользователя по id
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Пользователь
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Новое имя пользователя
                  required: false

      responses:
        200:
          description: Пользователь успешно изменен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
    delete:
      summary: Удалить пользователя по id
      description: Удаляет пользователя по id
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Пользователь
      responses:
        204:
          description: Пользователь успешно удален


  /users/{id}/todos:
    get:
      summary: Получить все тудушки пользователя
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Пользователь
        - Тудушка
      responses:
        200:
          description: Получить все тудушки пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/todoItem'
    post:
      summary: Добавить тудушку пользователю
      parameters:
        - $ref: '#/components/parameters/userId'
      tags:
        - Пользователь
        - Тудушка
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  required: true
                  description: Описание тудушки
                  example: Описание новой тудушки
      responses:
        201:
          description: Тудушка успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'

  /todos/{id}:
    get:
      summary: Получить тудушку по id
      description: Возвращает тудушку по id
      tags:
        - Тудушка
      parameters:
        - $ref: '#/components/parameters/todoId'
      responses:
        200:
          description: Возвращает тудушку по id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'
    patch:
      summary: Апдейт тудушки по id
      description: Апдейт тудушки по id
      tags:
        - Тудушка
      parameters:
        - $ref: '#/components/parameters/todoId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  required: false
                  description: Новое описание тудушки
                  example: Новое описание тудушки
                isDone:
                  type: boolean
                  required: false
                  description: Новый статус тудушки
                  example: true
      responses:
        200:
          description: Тудушка успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todoItem'
    delete:
      summary: Удалить тудушку по id
      description: Удалить тудушку по id
      tags:
        - Тудушка
      parameters:
        - $ref: '#/components/parameters/todoId'
      responses:
        204:
          description: Тудушка успешно удалена

components:
  parameters:
    userId:
      in: path
      name: id
      required: true
      schema:
        type: number
        description: id пользователя

    todoId:
      in: path
      name: id
      required: true
      schema:
        type: number
        description: id тудушки

  schemas:
    id:
      description: id сущности
      type: number
      example: 1

    user:
      description: пользователь
      type: object
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/id'
            - description: id пользователя
        name:
          type: string
          description: Имя пользователя
          example: 'User'

    todoItem:
      description: тудушка
      type: object
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/id'
            - description: id тудушки
        userId:
          allOf:
            - $ref: '#/components/schemas/id'
            - description: id пользователя, которому принадлежит тудушка
        description:
          type: string
          description: Описание задачи
        createdAt:
          type: string
          description: Дата создания
          example: '2020-06-30T18:25:02.495Z'
        updatedAt:
          type: string
          description: Дата последнего обновления
          example: '2020-06-30T18:25:02.495Z'
        isDone:
          type: boolean
          description: Статус задачи
          example: true
